### ISSUE TITLE
Initializing screen loops forever when only configured for flatpaks

### ISSUE THREAD

**Issue by Brorean** [vinifmor/bauh#112]
**Describe the bug**
I'm using Linux Mint 19.3 and Bauh is only configured for Flatpaks; this causes the _Initializing_ screen to loop forever until the _Skip_ button becomes available.

**Software Environment**
bauh version: 0.9.3
O.S: Linux Mint 19.3 
Python version: 3.6.9
bauh installation method: manual

**Comment by vinifmor** [comment]
Hi @Brorean , please, launch bauh through the command line (`bauh`) and paste any error output produced here.

**Comment by vinifmor** [comment]
I could reproduce here thanks to your PR description. The real problem is that the current initialization window cannot handle scenarios when there is no initialization task. I'm going to publish a proper fix soon. I would like to thank you for effort in coding a possible fix for the problem anyway.

**Comment by Brorean** [comment]
Sure no problem, I had fun going through the code

**Comment by vinifmor** [comment]
@Brorean , I've published the fix for the issue on the staging branch (https://github.com/vinifmor/bauh/commit/67d8204d19c16fdfed0aaf6ac8f5ca4a1431b461). Could you give me a feedback if it works now ?

**Comment by Brorean** [comment]
Yes this fix solves the problem.  Thank you

**Comment by vinifmor** [comment]
Great... the final release (0.9.4) should be available soon with this fix. I'm going to close your PR.
