### ISSUE TITLE
Recommendation: Rename installed appimages.

### ISSUE THREAD

**Issue by Predatux** [vinifmor/bauh#161]
I have found something that I think should be changed. For example, I have an appimage installed called "firefox", and I have created a launcher for that application, and I have indicated to the system that this application should open automatically at system startup, or that I look for it in the applications panel. The way to update from bauh is to rename the new appimage to "firefox (1)". When doing it that way, the launcher I created will not start by default, nor will the launcher I created work, and several versions of firefox (1), (2), etc. will appear in the system applications panel (1), (2), etc.
What I would like is that when bauh downloads a new version, rename the old version to, for example, "firefoxOLD", or "firefoxv.5.2", always leaving the most current version of the application with the original name "firefox" . Thus, if I have created a launcher, if the system starts the appimage at startup, it will always work, even after applying an update. It will also help to select the correct version from the system applications menu.
Thanks in advance

**Comment by vinifmor** [comment]
Hi @Predatux , this behavior is strange. Bauh automatically generates a Desktop Entry for AppImages that were installed through it and does not rename the added entries unless there is an previous existent one. Anyway, I'm going to review this scenario here. Thanks for reporting.

**Comment by Predatux** [comment]
![Bauh](https://user-images.githubusercontent.com/1749641/104440820-1c670880-5593-11eb-8265-036119459573.png)
![Bauh 2](https://user-images.githubusercontent.com/1749641/104440898-3acd0400-5593-11eb-95de-a097d950a0d2.png)

**Comment by Predatux** [comment]
It is possible that some appimage was already installed through the conventional method

**Comment by vinifmor** [comment]
Thanks for the information. I'm going to test this scenarios as well.

**Comment by vinifmor** [comment]
@Predatux , I've tried some scenarios here within KDE Plasma and Cinnamon and could not reproduce the behavior. I believe it has something to do with your desktop environment caching (Gnome, right ?).

To check the correct bauh behavior, try the following:
1. Locate the bauh desktop entry generated for your AppImage (it is stored ~/.local/share/applications following the standard **bauh_appimage_myappname.desktop**). e.g: for RPCS3 it should be ~/.local/share/applications/bauh_appimage_rpcs3.desktop.
2. Launch bauh and downgrade RPCS3
3. Check if the desktop entry was renamed
4. Now, upgrade RPCS3
5. Check if the desktop entry was renamed

If for some reason bauh renamed your AppImage desktop entry, I'm going to need more details about all your installed AppImages and desktop entries to investigate the issue.

**Comment by Predatux** [comment]
I have changed the default Appimages directory. I save them by default on a separate hard drive from the system. In my case, "/media/Software/Linux/AppImages"
I have tried to download the version as you have requested.
Attached screenshots.
![0](https://user-images.githubusercontent.com/1749641/104907758-de4c5900-5985-11eb-8902-82ac9dbdf3a7.png)
![1](https://user-images.githubusercontent.com/1749641/104907773-e2787680-5985-11eb-98d4-1d3a81f1c8a0.png)

**Comment by Predatux** [comment]
![3](https://user-images.githubusercontent.com/1749641/104907948-15bb0580-5986-11eb-812a-3e245e3c7ad2.png)

**Comment by vinifmor** [comment]
I'm not sure if I understood correctly how you manage you AppImages, but I'm going to explain how bauh manage an AppImage:

**Installation**
1. When an AppImage is requested to be installed, it will be stored at **~/.local/share/bauh/appimage/installed/new_appimage_name**. There you will find: the AppImage file, the application logo (e.g: logo.svg), and a file with the application data (data.json).
2. The AppImage shortcut will be generated at: **~/.local/share/applications** named as **bauh_appimage_new_appimage**

**Upgrade**
1. When an AppImage is requested to be upgrade, it will be first uninstalled (all files described previously will be removed).
2. Then it will repeat the steps described in **Installation**

If you want to use bauh to manage your AppImages, you cannot change its directory structure or touch the AppImage files directly otherwise errors are going to show up (like this popup when you asked for RPCS3 downgrading). But you can create symlinks for the places you want them to be stored. For instance:
```
ln -s /media/Software/Linux/AppImage ~/.local/share/bauh/appimage/installed
```

What I recommend: 
1. uninstall all your AppImages with bauh
2. delete all your manually created desktop entries for this AppImages
3. remove any AppImage left that you want to be managed by bauh
3. reinstall all these AppImages with bauh
