### ISSUE TITLE
All apps disappear after Refresh

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#24]
When I hit Refresh, all of the apps disappear.

**Comment by jayvdb** [comment]
This also happens after installing an app.
While the app is being installed, all apps not yet installed are shown.
Once the app is installed, it is shown in the list and the other apps not yet installed disappear.

**Comment by jayvdb** [comment]
After installing an app, and then restarting, the "available apps" list is shown, and then Refresh shows the installed apps with a "Apps" checkbox which does nothing.

**Comment by vinifmor** [comment]
Hi @jayvdb, the app is currently coded to work that way. I will explain these behaviors below:

* During bauh first refresh, if you have no applications installed (runtimes and libraries do not count), it will show some suggestions. It will not do that since the second refresh. This behavior has not been changed since version **0.5.X**. Otherwise you will not be able to manage your runtimes and libraries because it would keep showing suggestions instead of them. It's a behavior that could be discussed and improved, but it is not a bug.
* After you install a new application, bauh will refresh the table only with it. This behavior was implemented with the "quick launch" in mind. After the user install a new application, they will probably want to launch it. Keeping the other applications in the table could cause confusion.

**Comment by vinifmor** [comment]
If you change the application types in **0.7.2** and still have no apps installed, bauh will show the suggestions again.
