### ISSUE TITLE
Info window UI

### ISSUE THREAD

**Issue by jayvdb** [vinifmor/bauh#25]
The app info window feels like it needs some loving.
Each row has a Show button, which uses a large chunk of the window width.
The Show button appear even when the entire text is visible, so there is nothing more to show.
The user can scroll through the textboxes, so maybe the Show button should be dropped.

The value of each row is shown in a UI element which looks like an editable textbox.
It seems like the window would be work better with text areas with UI matching the background, i.e. labels.

**Comment by vinifmor** [comment]
Hi @jayvdb, I believe the show button is useful for large fields, because the info window could not handle several text areas in the same space. I tried scrollable text areas in the early versions, but had some issues in some desktop environments. I can test them again with the newest Qt versions. In the next feature version I will focus on the UI and see what can be improved. I'm actually thinking about changing the UI technology.
