### ISSUE TITLE
AppImage database files were not found. Some actions will not work properly.

### ISSUE THREAD

**Issue by topikarki** [vinifmor/bauh#289]
I have the error message AppImage database files were not found. Some actions will not work properly. And AppImages don't show up. I found an old issue with the same name as mine where it was told to add to path $HOME/.local/bin or something like that for bauh but I have bauh in the folder /usr/local/bin/, in fact I use AppImage version of bauh. In addition it was advised to install sqlite and fuse and then it should have worked. I was not able to install sqlite, what is the package name of it, sqlite3 ? Is there something else I should know? Database error comes only on the first visit to Bauh, how to invoke it.

**Comment by vinifmor** [comment]
After installing the dependencies, restart bauh and check the AppImage format on the settings window. The `sqlite3` name vary from distribution (on Arch is just `sqlite`, on Ubuntu `sqlite3`)

**Comment by topikarki** [comment]
It worked, thank you!

**Comment by vinifmor** [comment]
No worries

**Comment by Rik44444** [comment]
Hi,
I have this same problem, I just installed OpenSuse Tumbleweed (Geckolinux) 

I downloaded: 
bauh-0.10.5-x86_64_2c4f2b001ca3620e28be2dab9aeb3c8d.AppImage
and https://rpmfind.net/linux/RPM/opensuse/tumbleweed/x86_64/libqt5-dxcbplugin-5.0.70-3.1.x86_64.html 
and installed them. 
fuse was already installed on OpenSuse. 

I did what you described above, but in the Bauh settings I do not see any info about the AppImage format. HAs this been changed since you last posted this? Or am i looking with my nose? 

About system: 

KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.8-1-default (64-bit)

**Comment by vinifmor** [comment]
Hi @Rik44444 , to enable the AppImage support you need the following installed: `wget`, `sqlite3`, `fuse`. The error mentioned above is related to the AppImage database not being available on the system.

**Comment by adam-tj** [comment]
I have the same issue as @Rik44444 on OpenSUSE Tumbleweed. I have sqlite3, wget and fuse installed

**Comment by Niru2169** [comment]
I have the same issue...I'm also on Tumbleweed...
@adam-tj I've had issues while compile some other app, that said fuse wasn't installed, even though it was.
So is this a fuse thing?
