### ISSUE TITLE
stuck at initialization

### ISSUE THREAD

**Issue by kdvcodes** [vinifmor/bauh#92]
my bauh on Manjaro is stuck at 10% on refresing mirrors and 0% on syncing packages databases. Is there a way to fix this issue? I really like the new arch packages features so I don't want to disable it.

**Comment by vinifmor** [comment]
Refreshing mirrors can take some time depending of how many countries you are using. Bauh also sorts them by the fastest after the refresh to optimize the download speed.  At the moment is not possible to see the command line logs on initialization window, but this feature should be added on the next minor releases. Now you could disable the mirror refreshing during the initialization via the settings window and manually execute it via the custom actions button ("+"). A quick way to open the settings window is by typing on the command line: `bauh --settings`. Then go to the **Arch** tab and set **Refresh Mirrors On Startup** to **No**.

P.S: When this options is enabled, the database sync waits for it to complete before executing. That's why it stayed at 0%.

**Comment by kdvcodes** [comment]
I see. Thank you. And thanks for developing such an awesome program to manage package from all sources! I install on all systems I use that don't have this installed by default now :)

**Comment by vinifmor** [comment]
No worries. I'm glad the tool has been useful for you.

Cheers
